<?php $this->layout('layout::default', ['title' => 'EGLi (Manage) - Media bearbeiten']); ?>

<?php $this->push('stylesheet') ?>
<?php $this->end() ?>

<div class="container mb-5">
    <br>
    <div class="row">
        <div class="col">
            <h1 class="fw-bold">Media bearbeiten</h1>
        </div>
    </div>
    <?php $this->insert('app::media/mng/form-media-partial', ['mediaForm' => $mediaForm, 'redirectUrl' => $redirectUrl, 'datalist' => $datalist]); ?>
</div>