<?php $this->layout('layout::default', ['title' => 'EGLi (Manage) - Termine ']) ?>
<?php $this->push('stylesheet') ?>
<link href="/css/app/def-termin-calendar.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
<?php $this->end() ?>
<?php $this->push('javascript') ?>
<script src="/js/app/def-termin-calendar.js?u=<?= REFRESH_STATIC_FILES ?>" type="module"></script>
<?php $this->end() ?>
<!-- nav -->
<nav class="<?= $this->color()['bg-main-subtle'] ?> px-2 py-3">
    <div class="container-fluid d-flex justify-content-between row-gap-2 column-gap-3 flex-wrap">
        <a class="<?= $this->color()['text-main-emphasis'] ?> fs-5 fw-bold text-decoration-none" href="/manage/home-read">Home</a>
        <a class="<?= $this->color()['text-main-emphasis'] ?> fs-5 fw-bold text-decoration-none" href="/">Ansicht</a>
        <a class="<?= $this->color()['text-main-emphasis'] ?> fs-5 fw-bold text-decoration-none" href="/manage/media-read">Media</a>
        <a class="<?= $this->color()['text-main-emphasis'] ?> fs-5 fw-bold text-decoration-none" href="/cleanup">Cleanup</a>
        <a class="<?= $this->color()['text-main-emphasis'] ?> fs-5 fw-bold text-decoration-none" href="/app-logout" onclick="return confirm('Möchten Sie sich abmelden?')">Abmelden</a>
    </div>
</nav>
<?php $this->insert('app-partial::___calendar', [
    'data' => $terminCollection,
    'terminIdParam' => $terminIdParam,
    'dateParam' => $dateParam,
    'prevnextUrl' => '/manage/termin-calendar',
    'searchUrl' => '/manage/termin-search',
]) ?>