<?php $this->layout('layout::default', ['title' => 'EGLi (Manage) - Termin kopieren']); ?>

<?php $this->push('javascript') ?>
<script src="/js/app/mng-termin-write-modify.js?u=<?= REFRESH_STATIC_FILES ?>" type="module"></script>
<?php $this->end() ?>

<div class="container mb-5">
    <br>
    <div class="row">
        <div class="col">
            <h1 class="fw-bold">Eintrag kopieren</h1>
        </div>
    </div>
    <?php $this->insert('app::termin/mng/form-termin-partial', ['terminForm' => $terminForm, 'redirectUrl' => $redirectUrl, 'datalist' => $datalist]); ?>
</div>