<?php $this->layout('layout::default', ['title' => 'EGLi - Termine']) ?>
<?php $this->push('stylesheet') ?>
<link href="/css/app/def-termin-calendar.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
<?php $this->end() ?>
<?php $this->push('javascript') ?>
<script src="/js/app/def-termin-calendar.js?u=<?= REFRESH_STATIC_FILES ?>" type="module"></script>
<?php $this->end() ?>
<?php $this->insert('app-partial::___calendar', [
    'data' => $terminCollection,
    'terminIdParam' => $terminIdParam,
    'dateParam' => $dateParam,
    'prevnextUrl' => '/',
    'searchUrl' => '/search',
]) ?>