<?php

use App\Enum\TerminAnsichtEnum;
use App\Enum\TerminStatusEnum;
use App\Service\AttributeService;
use App\Service\HelperService;

// init
$terminCollection = $data;
$terminIdParam = $terminIdParam;
$dateParam = $dateParam;

// attributes
$elementAttributeService = new AttributeService([], $attributes ?? []);

// user
$loggedIn = isset($this->data['security']) ? $this->data['security']->getIdentity() : false;

?>
<!-- container -->
<div class="container-fluid p-0">
    <div class="fs-1 d-flex align-items-center justify-content-between py-1 px-3 mx-0 sticky-top <?= $this->color()['text-bg-main'] ?>">
        <a class="<?= $this->color()['link-main'] ?> text-decoration-none" href="<?= $prevnextUrl ?>?date=<?= (new DateTime($dateParam))->modify('first day of last month')->format('Y-m-d') ?>">
            <i class="bi bi-caret-left-fill"></i>
        </a>
        <span class="fw-light">
            <?= HelperService::format_displayDate($terminCollection->getReferenzDatum(), null, [
                'single' => $terminCollection->isReferenzThisYear() ? 'LLLL' : 'LLLL yy',
            ]) ?>
            <a class="<?= $this->color()['link-main'] ?>" href="<?= $searchUrl ?>"><i class="bi bi-search ms-3"></i></a>
        </span>
        <a class="<?= $this->color()['link-main'] ?> text-decoration-none" href="<?= $prevnextUrl ?>?date=<?= (new DateTime($dateParam))->modify('first day of next month')->format('Y-m-d') ?>">
            <i class="bi bi-caret-right-fill"></i>
        </a>
    </div>
    <div class="row m-0">
        <div class="offset-md-2 col-md-8 offset-lg-0 col-lg px-0">
            <ol class="p-0 mb-0 bg-dark-subtle">
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Mo</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Di</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Mi</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Do</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Fr</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-light-subtle text-secondary-emphasis">Sa</li>
                <li class="d-none d-lg-inline fw-bold p-2 fs-3 bg-body-tertiary text-secondary-emphasis">So</li>
                <?php foreach ($terminCollection as $termin) : ?>
                    <?php
                    $wrapperTag = TerminStatusEnum::GESTRICHEN->value === $termin['termin_status'] ? ['del'] : [];
                    ?>
                    <?php if ($terminCollection->isFirst() || $terminCollection->current['datum_datum'] !== $terminCollection->previous['datum_datum']) : ?>
                        <?php
                        $listClass = $terminCollection->isDatumSunday() ? 'bg-body-tertiary' : ($terminCollection->isDatumWithinReferenceMonth() ? 'bg-light-subtle' : 'bg-light-subtle');
                        $listClass .= !$terminCollection->isDatumWithinReferenceMonth() ? ' d-none d-lg-block' : '';
                        ?>
                        <li class="p-2 <?= $listClass ?>" <?= HelperService::getAnchorAttribute($termin['datum_datum']) ?>>
                            <div class="d-flex justify-content-between w-100 fw-light text-secondary-emphasis">
                                <div>
                                    <?php if ($terminCollection->isDatumFirstDayOfMonth()) : ?>
                                        <i class="bi bi-caret-right-fill <?= $this->color()['text-main'] ?> d-none d-lg-inline-block"></i>
                                    <?php elseif ($terminCollection->isDatumToday()) : ?>
                                        <i class="bi bi-check-circle-fill <?= $this->color()['text-main'] ?>"></i>
                                    <?php endif ?>
                                    <?php if (!$terminCollection->isDatumToday()) : ?>
                                        <span class="me-1">
                                            <?= HelperService::format_displayDate($terminCollection->getDatum(), null, ['single' => 'd',]) ?>
                                        </span>
                                    <?php endif ?>
                                    <?php if ($terminCollection->isDatumFirstDayOfMonth()) : ?>
                                        <span class="d-none d-lg-inline-block">
                                            <?= HelperService::format_displayDate($terminCollection->getDatum(), null, ['single' => 'MMMM',]) ?>
                                        </span>
                                    <?php endif ?>
                                </div>
                                <div>
                                    <span class="d-lg-none"><?= HelperService::format_displayDate($terminCollection->getDatum(), null, ['single' => 'eeee',]) ?></span>
                                    <?php if ($loggedIn) : ?>
                                        <a class="link-secondary" href="/manage/termin-insert/<?= $terminCollection->getDatum()->format('Y-m-d') ?>" title="Anlegen"><i class="bi bi-plus-circle ms-2"></i></a>
                                    <?php endif ?>
                                </div>
                            </div>
                        <?php endif ?>
                        <?php if ($terminCollection->hasTermin()) : ?>
                            <?php
                            $wrapperTag = TerminStatusEnum::GESTRICHEN->value === $termin['termin_status'] ? ['del'] : [];
                            $linkColor = TerminAnsichtEnum::NONE->value === $termin['termin_ansicht'] ? 'link-danger' : 'text-secondary-emphasis';
                            $highlightAttribute = $terminIdParam === $termin['termin_id'] ? HelperService::getAttribute('data-highlight', '1') : '';
                            ?>
                            <?php if ($termin['termin_image'] && $terminCollection->pushToMemory('image', $termin['termin_id'])) : ?>
                                <a href="/show/<?= $this->escape($termin['termin_id']) ?>?back=<?= $prevnextUrl ?>" class="<?= $linkColor ?> text-decoration-none" <?= HelperService::getAnchorAttribute($terminCollection->pushToMemory('calenderlist-anchor-id', $termin['termin_id'])) ?>>
                                    <img class="d-block d-lg-none my-2 w-100" src="<?= $this->media($termin['termin_image']) ?>?w=1400" alt="Thumbnail">
                                </a>
                            <?php endif ?>
                            <div class="body-text fw-light pb-2 <?php if (!$termin['termin_zeit_ganztags']) : ?>d-flex flex-wrap<?php endif ?>">
                                <div class="me-2 text-secondary">
                                    <?php if (!$termin['termin_zeit_ganztags']) : ?>
                                        <?= $this->escape(substr($termin['termin_zeit_start'], 0, 5)) ?>
                                    <?php endif; ?>
                                </div>
                                <div <?= $highlightAttribute ?>>
                                    <?php $this->insert('partial::wrappertags', ['type' => 'open', 'tags' => $wrapperTag]) ?>
                                    <?php if (TerminStatusEnum::MITTEILUNG->value === $termin['termin_status']) : ?>
                                        <i class="bi bi-info-circle-fill me-1 <?= $this->color()['text-main'] ?>"></i>
                                    <?php endif ?>
                                    <a href="/show/<?= $this->escape($termin['termin_id']) ?>?back=<?= $prevnextUrl ?>" class="<?= $linkColor ?> text-decoration-none" <?= HelperService::getAnchorAttribute($terminCollection->pushToMemory('calenderlist-anchor-id', $termin['termin_id'])) ?>>
                                        <span class="me-2">
                                            <?= $this->escape($termin['termin_betreff']) ?>
                                        </span>
                                        <?php if (!$termin['termin_zeige_einmalig'] && $termin['_anzahl_tage'] > 1) : ?>
                                            <span class="opacity-50 me-2">
                                                (Tag&nbsp;<?= intval((new DateTime($termin['termin_datum_start']))->diff(new DateTime($termin['datum_datum']))->format('%R%a')) + 1 ?>/<?= $termin['_anzahl_tage'] ?>)
                                            </span>
                                        <?php endif; ?>
                                        <?php if ($termin['termin_mitvon']) : ?>
                                            <span class="me-2">
                                                (<?= $this->escape($termin['termin_mitvon']) ?>)
                                            </span>
                                        <?php endif; ?>
                                    </a>
                                    <?php if ($termin['termin_link'] || $termin['termin_link2']) : ?>
                                        <?php if ($termin['termin_link']) : ?>
                                            <a class="me-2 text-decoration-none" href="<?= $this->escape($termin['termin_link']) ?>">
                                                <?= $this->escape($termin['termin_link_titel'] ?? 'Link') ?>
                                            </a>
                                        <?php endif ?>
                                        <?php if ($termin['termin_link2']) : ?>
                                            | <a class="mx-2 text-decoration-none" href="<?= $this->escape($termin['termin_link2']) ?>">
                                                <?= $this->escape($termin['termin_link2_titel'] ?? 'Link') ?>
                                            </a>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php if ($termin['termin_text']) : ?>
                                        <a href="/show/<?= $this->escape($termin['termin_id']) ?>?back=<?= $prevnextUrl ?>" class="<?= $linkColor ?> text-decoration-none" <?= HelperService::getAnchorAttribute($terminCollection->pushToMemory('calenderlist-anchor-id', $termin['termin_id'])) ?>>
                                            <div class="opacity-50">
                                                <?= nl2br($this->escape(HelperService::string_substrWords($termin['termin_text'], 30))) ?>
                                            </div>
                                        </a>
                                    <?php endif ?>
                                    <?php if ((new DateTime($termin['datum_datum']))->format('Y-m-d') !== (new DateTime())->format('Y-m-d')) : ?>
                                        <?php if ($termin['_is_new'] || $termin['_is_updated']) : ?>
                                            <div>
                                                <?php if ($termin['_is_new']) : ?>
                                                    <!-- new indicator -->
                                                    <span class="badge <?= $this->color()['text-bg-indicator'] ?> fw-bold mt-1">Neu</span>
                                                <?php elseif ($termin['_is_updated']) : ?>
                                                    <!-- update indicator -->
                                                    <span class="badge <?= $this->color()['text-bg-indicator'] ?> fw-bold mt-1">Aktualisiert</span>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php $this->insert('partial::wrappertags', ['type' => 'close', 'tags' => $wrapperTag]) ?>
                                    <?php if ($loggedIn) : ?>
                                        <div>
                                            <?php if ($termin['_fehlbuchung'] && ($termin['termin_zeige_konflikt'])) : ?>
                                                <div class="btn-group" role="group">
                                                    <?php foreach (explode('+++', $termin['_fehlbuchung']) as $k) : ?>
                                                        <?php $v = explode('---', $k) ?>
                                                        <?php if (strtotime($termin['datum_datum']) >= strtotime($v[4]) && strtotime($termin['datum_datum']) <= strtotime($v[5])) : ?>
                                                            <span class="badge bg-danger-subtle text-danger-emphasis fw-bold mt-1"><?= $this->escape($v[1]) ?><?php if ($v[2]) : ?> - <?= $this->escape($v[2]) ?><?php endif ?></span>
                                                        <?php endif ?>
                                                    <?php endforeach; ?>
                                                </div>
                                            <?php endif ?>
                                            <?php if ($termin['termin_notiz']) : ?>
                                                <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1">Notiz</span>
                                            <?php endif; ?>
                                            <?php if ($termin['termin_zeige_einmalig']) : ?>
                                                <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1">Einmalig</span>
                                            <?php endif; ?>
                                            <?php if ($termin['termin_zeige_tagezuvor']) : ?>
                                                <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1">Tage zuvor <?= $termin['termin_zeige_tagezuvor'] ?></span>
                                            <?php endif; ?>
                                            <?php if (!$termin['termin_aktiviere_drucken']) : ?>
                                                <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1 text-decoration-line-through">Druckrelevant</span>
                                            <?php endif; ?>
                                            <?php if (!$termin['termin_ist_konfliktrelevant']) : ?>
                                                <!-- <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1 text-decoration-line-through">Konfliktrelevant</span> -->
                                            <?php endif; ?>
                                            <?php if (!$termin['termin_zeige_konflikt']) : ?>
                                                <!-- <span class="badge <?= $this->color()['bg-main-subtle'] ?> <?= $this->color()['text-main-emphasis'] ?> fw-bold mt-1 text-decoration-line-through">Konfliktanzeige</span> -->
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($loggedIn) : ?>
                                            <!-- Button trigger modal -->
                                            <button type="button" class="ps-0 btn btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal<?= $termin['termin_id'] ?>">
                                                <i class="bi bi-list"></i>
                                            </button>
                                            <!-- Modal -->
                                            <div class="modal fade" id="exampleModal<?= $termin['termin_id'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel<?= $termin['termin_id'] ?>" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h3 class="modal-title" id="exampleModalLabel<?= $termin['termin_id'] ?>">Aktion</h3>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="list-group list-group-flush">
                                                                <a class="ps-0 list-group-item list-group-item-action" href="/manage/termin-update/<?= $termin['termin_id'] ?>">Bearbeiten</a>
                                                                <a class="ps-0 list-group-item list-group-item-action" href="/manage/termin-copy/<?= $termin['termin_id'] ?>">Kopieren</a>
                                                                <a class="ps-0 list-group-item list-group-item-action" href="/manage/termin-delete/<?= $termin['termin_id'] ?>">Löschen</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endif ?>
                                    <?php endif ?>
                                </div>
                            </div>
                        <?php endif ?>
                        <?php if ($terminCollection->isLast() || $terminCollection->current['datum_datum'] !== $terminCollection->next['datum_datum']) : ?>
                        </li>
                    <?php endif ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>