<?php $this->layout('layout::default', ['title' => 'EGLi (Manage) - Home']) ?>
<?php $this->push('stylesheet') ?>
<style>
    body {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100dvh;
    }

    nav {
        display: grid;
        grid-template-rows: repeat(auto-fit, 1fr);
        grid-template-columns: repeat(1, 1fr);
        column-gap: 1rem;
        row-gap: 1rem;
    }

    nav>a {
        font-size: 24pt !important;
        font-weight: bold !important;
        padding: 1rem !important;
        display: flex !important;
        align-items: center !important;
        justify-content: center !important;
    }

    /* Small devices (landscape phones, 576px and up) */
    @media (min-width: 576px) {
        nav {
            grid-template-rows: repeat(auto-fit, 1fr);
            grid-template-columns: repeat(2, 1fr);
        }
    }

    /* Medium devices (tablets, 768px and up) */
    @media (min-width: 768px) {
        nav {
            grid-template-rows: repeat(3, 1fr);
            grid-template-columns: repeat(3, 1fr);
        }

        #item-1 {
            grid-row-end: span 2;
        }

        #item-3 {
            grid-row-end: span 2;
        }
    }
</style>
<?php $this->end() ?>
<!-- nav -->


<div class="container">
    <nav class="mx-2 my-3">
        <a id="item-1" class="btn btn-secondary" role="button" href="/manage/termin-calendar">
            Termine
        </a>
        <a id="item-2" class="btn btn-warning" role="button" href="/manage/home-stats?gip=1">
            Stats
        </a>
        <a id="item-3" class="btn btn-info" role="button" href="/manage/media-read">
            Media
        </a>
        <a id="item-4" class="fw-bold bg-light text-dark">
            <?= $this->escape($this->quote()) ?>
        </a>
        <a id="item-5" class="btn btn-success" role="button" href="/manage/home-tabellen">
            Tabellen
        </a>
        <a id="item-6" class="btn btn-danger" role="button" href="/manage/home-initconfig">
            App
        </a>
        <a id="item-7" class="btn btn-light border border-3" href="/app-logout">
            Abmelden
        </a>
    </nav>
</div>