<!DOCTYPE html>
<html lang="de" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= $this->section('meta') ?>
    <!-- Icons -->
    <title><?= $this->e($title) ?></title>
    <link rel="icon" sizes="192x192" href="/img/logo_180_180.png" type="image/png">
    <link rel="shortcut icon" href="/img/logo_32_32.png" type="image/png">
    <link rel="apple-touch-icon" href="/img/logo_180_180.png" type="image/png">
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="/css/main.css?u=<?= REFRESH_STATIC_FILES ?>" rel="stylesheet">
    <?= $this->section('stylesheet') ?>
    <!-- JavaScript -->
    <script>
        let theme = (new URL(document.location)).searchParams.get("theme");
        if ('light' === theme || 'dark' === theme) {
            sessionStorage.setItem('theme', theme);
        } else if (sessionStorage.getItem('theme')) {
            theme = sessionStorage.getItem('theme');
        } else if (!sessionStorage.getItem('theme')) {
            if (window.matchMedia('(prefers-color-scheme: dark)').matches)
                theme = 'dark';
            else
                theme = 'light';
        }
        document.documentElement.setAttribute('data-bs-theme', theme);
    </script>
    <script defer src="/js/main.js?u=<?= REFRESH_STATIC_FILES ?>"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>

<body data-page-datetime="<?= date("Y-m-d-H-i-s") ?>" class="bg-light-subtle text-body-emphasis">
    <?= $this->section('content') ?>
    <!-- top corner button -->
    <button class="corner_button top_corner_button" onclick="topFunction()" id="top_corner_button" title="Go to top">
        <i class="bi bi-caret-up-fill"></i>
    </button>
    <!-- flash messages -->
    <?php if (isset($notifications)) : ?>
        <?php $this->insert('partial::flash') ?>
    <?php endif; ?>
    <?= $this->section('javascript') ?>
</body>

</html>