<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */

declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            // handler
            App\Handler\Auth\Def\LoginHandler::class       => App\Handler\Auth\Def\LoginHandlerFactory::class,
            App\Handler\Auth\Def\LogoutHandler::class      => App\Handler\Auth\Def\LogoutHandlerFactory::class,
            App\Handler\Home\Def\CleanupHandler::class     => App\Handler\Home\Def\CleanupHandlerFactory::class,
            App\Handler\Home\Def\TestHandler::class     => App\Handler\Home\Def\TestHandlerFactory::class,
            App\Handler\Home\Mng\HomeReadHandler::class             => App\Handler\Home\Mng\HomeReadHandlerFactory::class,
            App\Handler\Home\Mng\HomeInitconfigHandler::class             => App\Handler\Home\Mng\HomeInitconfigHandlerFactory::class,
            App\Handler\Home\Mng\HomePhpinfoHandler::class             => App\Handler\Home\Mng\HomePhpinfoHandlerFactory::class,
            App\Handler\Home\Mng\HomeTabellenHandler::class             => App\Handler\Home\Mng\HomeTabellenHandlerFactory::class,
            App\Handler\Home\Mng\HomeStatsHandler::class             => App\Handler\Home\Mng\HomeStatsHandlerFactory::class,
            App\Handler\Media\Def\MediaIndexHandler::class    => App\Handler\Media\Def\MediaIndexHandlerFactory::class,
            App\Handler\Media\Mng\MediaReadHandler::class           => App\Handler\Media\Mng\MediaReadHandlerFactory::class,
            App\Handler\Media\Mng\MediaVersionHandler::class           => App\Handler\Media\Mng\MediaVersionHandlerFactory::class,
            App\Handler\Media\Mng\MediaDeleteHandler::class          => App\Handler\Media\Mng\MediaDeleteHandlerFactory::class,
            App\Handler\Media\Mng\MediaInsertHandler::class          => App\Handler\Media\Mng\MediaInsertHandlerFactory::class,
            App\Handler\Media\Mng\MediaUpdateHandler::class          => App\Handler\Media\Mng\MediaUpdateHandlerFactory::class,
            App\Handler\Termin\Def\TerminIcsHandler::class    => App\Handler\Termin\Def\TerminIcsHandlerFactory::class,
            App\Handler\Termin\Def\TerminShowHandler::class   => App\Handler\Termin\Def\TerminShowHandlerFactory::class,
            App\Handler\Termin\Def\TerminCalendarHandler::class   => App\Handler\Termin\Def\TerminCalendarHandlerFactory::class,
            App\Handler\Termin\Def\TerminSearchHandler::class  => App\Handler\Termin\Def\TerminSearchHandlerFactory::class,
            App\Handler\Termin\Mng\TerminCalendarHandler::class         => App\Handler\Termin\Mng\TerminCalendarHandlerFactory::class,
            App\Handler\Termin\Mng\TerminSearchHandler::class         => App\Handler\Termin\Mng\TerminSearchHandlerFactory::class,
            App\Handler\Termin\Mng\TerminCopyHandler::class        => App\Handler\Termin\Mng\TerminCopyHandlerFactory::class,
            App\Handler\Termin\Mng\TerminDeleteHandler::class        => App\Handler\Termin\Mng\TerminDeleteHandlerFactory::class,
            App\Handler\Termin\Mng\TerminInsertHandler::class        => App\Handler\Termin\Mng\TerminInsertHandlerFactory::class,
            App\Handler\Termin\Mng\TerminUpdateHandler::class        => App\Handler\Termin\Mng\TerminUpdateHandlerFactory::class,
            // middleware
            App\Middleware\HistoryMiddleware::class          => App\Middleware\HistoryMiddlewareFactory::class,
            App\Middleware\RedirectMiddleware::class         => App\Middleware\RedirectMiddlewareFactory::class,
            App\Middleware\TemplateDefaultsMiddleware::class => App\Middleware\TemplateDefaultsMiddlewareFactory::class,
            App\Middleware\UrlpoolMiddleware::class         => App\Middleware\UrlpoolMiddlewareFactory::class,
        ],
    ],
];
